Update ABI resolution scheme
KeystoneHQ/Keystone-cold-app pull request #4
Opened 2021-07-16 06:05 UTC by finalstatics

Update ABI resolution scheme

2021-07-19 10:16 UTC, aaronisme requested changes

2021-07-19 10:16 UTC, aaronisme commented on coinlib/src/main/java/com/keystone/coinlib/utils/AbiLoader.java
> +    public static final String INDEX_JSON_SDCARD_PATH = "contracts" + File.separator + "ethereum";
refactor the duplicate logic

2021-07-19 10:26 UTC, aaronisme commented on coinlib/src/main/java/com/keystone/coinlib/utils/AbiLoader.java
> +            db.close();
cursor should be close too？

2021-07-20 02:48 UTC, aaronisme commented on coinlib/src/main/java/com/keystone/coinlib/coins/ETH/EthImpl.java
> +                Contract dataFromTFCard = TFDBLoader.getDataFromTFCard(rawTx.getTo());
TFDBLoader -> ContactExternalDbLoader

2021-07-20 02:48 UTC, aaronisme commented on coinlib/src/main/java/com/keystone/coinlib/coins/ETH/EthImpl.java
> +                Contract dataFromTFCard = TFDBLoader.getDataFromTFCard(rawTx.getTo());
dataFromTFCard -> ContractData

2021-07-20 03:40 UTC, aaronisme approved these changes
LGTM

2021-07-20 03:43 UTC, soralit commented on app/src/main/java/com/keystone/cold/viewmodel/EthTxConfirmViewModel.java
> +import com.keystone.coinlib.utils.ContactExternalDbLoader;
typo

2021-07-20 05:11 UTC, aaronisme approved these changes

2021-07-20 05:17 UTC, merged